version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api-gateway:
    image: node:18-alpine
    container_name: api-gateway
    working_dir: /usr/src/app
    volumes:
      - ./api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    command: sh -c "npm install && npm run start:dev"
    tty: true

  user-service:
    image: node:18-alpine
    container_name: user-service
    working_dir: /usr/src/app
    volumes:
      - ./user-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: mydb
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    command: sh -c "npm install && npm run start:dev"
    tty: true

  room-service:
    image: node:18-alpine
    container_name: room-service
    working_dir: /usr/src/app
    volumes:
      - ./room-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: mydb
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    command: sh -c "npm install && npm run start:dev"
    tty: true

  booking-service:
    image: node:18-alpine
    container_name: booking-service
    working_dir: /usr/src/app
    volumes:
      - ./booking-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: mydb
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    command: sh -c "npm install && npm run start:dev"
    tty: true